name: Bug report
description: Report a reproducible problem
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Tell us what you saw.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Include code snippets or a minimal repro if possible.
      placeholder: "1. …\n2. …\n3. …"
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Node version, OS, package versions, etc.
      placeholder: "Node: \nOS: \nPackage(s): "
    validations:
      required: true

