name: Release / Prepare PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Checkout workflow modules
        uses: actions/checkout@v6
        with:
          ref: ${{ github.workflow_sha }}
          path: .github/automation
          sparse-checkout: .github
          persist-credentials: false
      - name: Validate repository
        uses: ./.github/automation/.github/actions/validation/repository
        with:
          registry-url: https://registry.npmjs.org
      - name: Release Please (stable)
        uses: ./.github/automation/.github/actions/release/release-please
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          mode: prepare
        id: release
    timeout-minutes: 20
