name: Release / Prepare PR

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: release-please-prepare
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - name: Checkout workflow modules
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ref: ${{ github.workflow_sha }}
          path: .github/automation
          sparse-checkout: .github
          persist-credentials: false
      - name: Release Please (stable)
        uses: ./.github/automation/.github/actions/release/release-please
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          mode: prepare
        id: release
    timeout-minutes: 20
